# Jykell configuration

markdown: redcarpet
# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "footnotes","space_after_headers","highlight","underline","quote","lax_spacing"]
# Feed!

highlighter: rouge
paginate: 10
language: 'en-us'

# Website info
name: "梦麟繁花"
description: "Laziness, Impatience and Hubris."
meta_description: 梦魇的个人博客
meta_keywords: moonagic, 梦魇, 梦麟繁花, 微梦一生, jekyll, blog, 博客, 独立博客, github
url: "https://blog.remaindertime.cn"

short_url: 'moonagic.com'
google_analytics: 'UA-74995541-1'
google_analytics_url: 'http://source.remaindertime.cn/'
cdn_url: 'http://source.remaindertime.cn/'
# disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'

# host: 0.0.0.0
# port: 4000

# Permalinks
permalink: /:title/
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate, rouge, jekyll-sitemap, jekyll-mermaid]

# mermaid
mermaid:
  src: '/assets/js/mermaid.min.js'

excerpt_separator:  '<!-- more -->'

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
